name: .NET Core Desktop

on:
  push:
    branches: [ "main", "release", "develop"]
  pull_request:
    branches: [ "main", "release", "develop" ]

jobs:
  test_applicatie:
    runs-on: windows-latest
    steps:
      - name: Haal de repository op
        uses: actions/checkout@v4
 
      # Install the .NET Core workload
      - name: Install .NET Core
        uses: actions/setup-dotnet@v4
        with:
             dotnet-version: 8.0.x
 
      - name: Installeer MAUI workloads
        run: dotnet workload install maui
 
      - name: Herstel afhankelijkheden
        run: dotnet restore
 
      - name: Bouw de applicatie
        run: dotnet build --configuration Release -f net8.0-windows10.0.19041.0 /p:RuntimeIdentifierOverride=win-x64
 
      - name: Voer unit tests uit
        run: dotnet test --configuration Release --no-restore --no-build --verbosity normal
                       
                             
